services:
  # ==================================
  # NATS_SERVERS
  # ==================================
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  # ==================================
  # CLIENT_GATEWAY
  # ==================================
  client-gateway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      PORT: 3000
      NATS_SERVERS: ${NATS_SERVERS}
    restart: unless-stopped

  # ==================================
  # PRODUCTS_MICROSERVICE
  # ==================================
  products-microservice:
    build: ./products-microservice
    ports:
      - "${PRODUCTS_MS_PORT}:3001"
    volumes:
      - ./products-microservice/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      PORT: ${PRODUCTS_MS_PORT}
      NATS_SERVERS: ${NATS_SERVERS}
      DATABASE_URL: ${PRODUCTS_DATABASE_URL}
    restart: unless-stopped

  # ==================================
  # ORDERS_MICROSERVICE
  # ==================================
  orders-microservice:
    build: ./orders-microservice
    ports:
      - "${ORDERS_MS_PORT}:3002"
    volumes:
      - ./orders-microservice/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      PORT: ${ORDERS_MS_PORT}
      NATS_SERVERS: ${NATS_SERVERS}
      DATABASE_URL: postgresql://${ORDERS_DB_USER}:${ORDERS_DB_PASSWORD}@orders-microservice-db:5432/${ORDERS_DB_NAME}?schema=public
    depends_on:
      - orders-microservice-db
    restart: unless-stopped

  # ==================================
  # ORDERS_MICROSERVICE_DB
  # ==================================
  orders-microservice-db:
    image: postgres:16.2-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${ORDERS_DB_USER}
      POSTGRES_PASSWORD: ${ORDERS_DB_PASSWORD}
      POSTGRES_DB: ${ORDERS_DB_NAME}
    volumes:
      - orderspgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${ORDERS_DB_USER} -d ${ORDERS_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ==================================
  # PAYMENTS_MICROSERVICE
  # ==================================
  payments-microservice:
    build: ./payments-microservice
    ports:
      - "${PAYMENTS_MS_PORT}:3003"
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      PORT: ${PAYMENTS_MS_PORT}
      NATS_SERVERS: ${NATS_SERVERS}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL}
    restart: unless-stopped

volumes:
  orderspgdata:
